# Generated by Django 5.0.14 on 2025-04-29 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolumler',
            fields=[
                ('bolum_id', models.AutoField(primary_key=True, serialize=False)),
                ('bolum_adi', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Derslikler',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('derslik_id', models.CharField(max_length=50, unique=True)),
                ('kapasite', models.IntegerField()),
                ('statu', models.CharField(choices=[('LAB', 'Laboratuvar'), ('NORMAL', 'Normal')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fakulte',
            fields=[
                ('fakulte_id', models.AutoField(primary_key=True, serialize=False)),
                ('fakulte_adi', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dersler',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('sinif', models.IntegerField()),
                ('ders_kodu', models.CharField(max_length=50)),
                ('ders_adi', models.CharField(max_length=255)),
                ('haftalik_saat', models.IntegerField()),
                ('online', models.CharField(blank=True, max_length=255, null=True)),
                ('zorunlu_saat', models.CharField(blank=True, max_length=255, null=True)),
                ('statu', models.CharField(choices=[('LAB', 'Laboratuvar'), ('NORMAL', 'Normal')], max_length=10)),
                ('bolum', models.ForeignKey(db_column='bolum_id', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CourseSchedule.bolumler')),
                ('fakulte', models.ForeignKey(db_column='fakulte_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='CourseSchedule.fakulte')),
            ],
        ),
        migrations.AddField(
            model_name='bolumler',
            name='fakulte',
            field=models.ForeignKey(db_column='fakulte_id', on_delete=django.db.models.deletion.CASCADE, to='CourseSchedule.fakulte'),
        ),
        migrations.CreateModel(
            name='Ogrenciler',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('sinif', models.IntegerField()),
                ('numara', models.CharField(max_length=50, unique=True)),
                ('bolum', models.ForeignKey(db_column='bolum_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='CourseSchedule.bolumler')),
                ('fakulte', models.ForeignKey(db_column='fakulte_id', on_delete=django.db.models.deletion.CASCADE, to='CourseSchedule.fakulte')),
            ],
        ),
        migrations.CreateModel(
            name='OgrenciDers',
            fields=[
                ('std_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('ders_id', models.ForeignKey(db_column='course_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='CourseSchedule.dersler')),
                ('ogrenci_id', models.ForeignKey(db_column='student_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='CourseSchedule.ogrenciler')),
            ],
        ),
        migrations.CreateModel(
            name='OgretimGorevlileri',
            fields=[
                ('ogrv_id', models.AutoField(primary_key=True, serialize=False)),
                ('ogretim_gorevlisi', models.CharField(max_length=255, unique=True)),
                ('pazartesi', models.CharField(blank=True, max_length=255, null=True)),
                ('sali', models.CharField(blank=True, max_length=255, null=True)),
                ('carsamba', models.CharField(blank=True, max_length=255, null=True)),
                ('persembe', models.CharField(blank=True, max_length=255, null=True)),
                ('cuma', models.CharField(blank=True, max_length=255, null=True)),
                ('fakulte', models.ForeignKey(db_column='fakulte_id', on_delete=django.db.models.deletion.CASCADE, to='CourseSchedule.fakulte')),
            ],
        ),
        migrations.AddField(
            model_name='dersler',
            name='ogretim_uyesi',
            field=models.ForeignKey(db_column='ogrv_id', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CourseSchedule.ogretimgorevlileri'),
        ),
    ]
