# Generated by Django 5.0.14 on 2025-05-01 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseSchedule', '0002_ogrenciler_sifre_ogretimgorevlileri_kullanici_adi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OgrenciDers',
            fields=[
                ('std_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('ders', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='CourseSchedule.dersler')),
                ('ogrenci', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='CourseSchedule.ogrenciler')),
            ],
            options={
                'unique_together': {('ogrenci', 'ders')},
            },
        ),
    ]
